version: '2'
services:
  hubot:
    build: .
    env_file:
      - ENV
    #volumes:
      #- /home/hubot/bot/
  redis:
    image: redis:latest
    command: redis-server --appendonly yes --auto-aof-rewrite-min-size 32mb --auto-aof-rewrite-percentage 50
    volumes:
      - ./hubot-data:/data
